# -*- coding: utf-8 -*-
"""19110290_THPTTT_Tuan7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17HxHwA1dhcASlX5KFBC-nFnYX0h9KKGO

# Họ & Tên: Phạm Nguyễn Phương Duy
# MSSV: 19110290

# Bài 1
"""

def majority_element(arr):
    n = len(arr)
    count = [0] * 10 # Khởi tạo mảng count với kích thước 10
    element = [None] * 10 # Khởi tạo mảng element với kích thước 10

    for i in range(n):
        j = 0
        while j < 10:
            if element[j] == arr[i]: # Nếu phần tử hiện tại xuất hiện trong mảng element
                count[j] += 1 # Tăng giá trị tương ứng trong mảng count lên 1
                break
            elif count[j] == 0: # Nếu có vị trí nào trong mảng count có giá trị bằng 0
                element[j] = arr[i] # Gán giá trị của phần tử hiện tại vào vị trí tương ứng trong mảng element
                count[j] = 1 # Gán giá trị tương ứng trong mảng count bằng 1
                break
            j += 1
        else:
            for k in range(10):
                count[k] -= 1 # Giảm giá trị của tất cả các phần tử trong mảng count đi 1

    result = []
    for i in range(10):
        actual_count = sum(1 for x in arr if x == element[i]) # Tính số lần xuất hiện thực sự của phần tử trong mảng arr
        if actual_count > n/10: # Nếu số lần xuất hiện này lớn hơn n/10
            result.append(element[i]) # Thêm phần tử đó vào danh sách kết quả

    return result

# Test
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 3, 6, 9]
result = majority_element(arr)
if len(result) == 0:
    print("Không có phần tử lấn chiếm cấp độ 10")
else:
    print(f"Phần tử lấn chiếm cấp độ 10: {result}")

"""# Bài 2"""

import random

def merge_arrays(A, B):
    # Khởi tạo kết quả
    result = []
    
    # Khởi tạo chỉ số cho hai mảng
    i = j = 0
    
    # Duyệt qua hai mảng và thêm phần tử nhỏ hơn vào kết quả
    while i < len(A) and j < len(B):
        if A[i] < B[j]:
            result.append(A[i])
            i += 1
        else:
            result.append(B[j])
            j += 1
    
    # Thêm các phần tử còn lại của mảng A (nếu có)
    while i < len(A):
        result.append(A[i])
        i += 1
    
    # Thêm các phần tử còn lại của mảng B (nếu có)
    while j < len(B):
        result.append(B[j])
        j += 1
    
    return result

# Test

N = 10 # Số lượng phần tử trong mỗi mảng
A = sorted([random.randint(1, 100) for _ in range(N)])
B = sorted([random.randint(1, 100) for _ in range(N)])

print(f"Mảng A: {A}")
print(f"Mảng B: {B}")
print(f"Mảng được sắp xếp: {merge_arrays(A, B)}")