# -*- coding: utf-8 -*-
"""19110290_THPTTT_Tuan9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hz3Ggndyi14S5Gq1iuJrD-MaRo2vdtvy

# Họ & Tên: Phạm Nguyễn Phương Duy
# MSSV: 19110290
"""

#Hàm tìm Tổng bình phương các chữ số
def sum_of_squares_of_digits(n):
    sum = 0
    while n > 0:
        digit = n % 10
        sum += digit ** 2
        n //= 10
    return sum

#Hàm tìm Dãy số 
def find_sequence(N):
    sequence = []
    seen = set()
    while N not in seen:
        sequence.append(N)
        seen.add(N)
        N = sum_of_squares_of_digits(N)
    return sequence

#Test
N = 85
sequence = find_sequence(N)
output = ' → '.join(map(str, sequence))
print(f"Chu kỳ tuần hoàn nhỏ nhất của dãy số đó với giá tri N = {N} là {len(sequence)} chu kỳ")
print(f"Với N = {N}, dãy sẽ có giá trị lần lượt như sau:")
print(output)